### ISSUE TITLE
Question: Tabbar controller?

### ISSUE THREAD

**Issue by devJoshLopez** [hyperoslo/Whisper#106]
How can i use Whisper from a tabbarcontroller without a navigationcontroller? I am new to ios, if I cant do it in a tabbarcontroller what should i do in my storyboard to make it work?

**Comment by RamonGilabert** [comment]
Hey Josh! Thanks for this issue. I am afraid you cannot at the moment, and we were not planning to add this feature any time soon.

With that being said, you have a `UITabBarController` that contains multiple controllers.

If you set a `UINavigationController` and hide the navigation bar, you could "fake" a Whisper, but I am not sure this is what you want.

What is the issue that you want to solve? Because maybe then a `Whistle` could do the job:

![whistle-information](https://cloud.githubusercontent.com/assets/6138120/18549478/0120fa36-7b4f-11e6-9f86-eef1ab877ec4.png)

I'll close the issue for now, but feel free to reply to this message and I can assist you further on :)
