### ISSUE TITLE
Question: present Whisper from RootViewController

### ISSUE THREAD

**Issue by oferRounds** [hyperoslo/Whisper#123]
Hi,
I use a tab bar controller in my app, and I'd like to show Whisper in the way that it will still be visible even if the user switched to another tab. Is that thing possible?

**Comment by RamonGilabert** [comment]
Hey @oferRounds!

Sadly, it's not, since a Whisper needs a UINavigationController (for now), I believe that you could do a Whistle, that goes independent to the controller, or, another solution would be (a bit weird though), to have a UINavigationController with a hidden navigation bar that contains a UITabBarController, which contains UINavigationControllers / UIViewControllers inside.

Sorry about that.

**Comment by oferRounds** [comment]
Hey @RamonGilabert!

Thanks for your answer! I'll see about your idea

Thanks!!!

**Comment by RamonGilabert** [comment]
Feel free to comment in this issue if you have trouble, or open a new issue if something appears! 😊

**Comment by oferRounds** [comment]
I will, thanks! 👍
