### ISSUE TITLE
Whisper frame is not adjusted on orientation change

### ISSUE THREAD

**Issue by andriichernenko** [hyperoslo/Whisper#19]
Steps to reproduce: 
1. Show whisper
2. Change device orientation while it is still visible

Result:
Device width changes, but whisper width remains the same.

**Comment by zenangst** [comment]
Hey @deville, thanks for reporting this issue. Right of the bat, I think this could be fixed by adding an observer on the `WhisperView`. Namely `UIDeviceOrientationDidChangeNotification`, so if the orientation were to change while it is being displayed, it would re-render itself in the right position. We will look into this issue and keep you posted. Thanks for using and supporting `Whisper` :heart:

**Comment by haithngnbak** [comment]
I have tried show Whisper in navigationcontroller that has a UITableView and it make the tableview wrong   top margin.
