### ISSUE TITLE
Feature: add keyboard input option as in the native Push banner

### ISSUE THREAD

**Issue by oferRounds** [hyperoslo/Whisper#29]
And - thanks for this really really great library!

**Comment by RamonGilabert** [comment]
Hey @oferRounds :) Thank you for using Whisper!

Although I like the idea, I'm not sure it makes perfect sense for it. Shout is something that you use inside your app because the native push doesn't show up. But there's a reason for that, you are inside the app already, you could send your user for the answer and that's it.

The native push banner keyboard input is thought for you to not lose context, although if you are inside the app already, you don't lose that much context.

I'll leave the issue open for now though.

**Comment by oferRounds** [comment]
Hi Ramon

I understand what you're saying, thanks for replying!
