### ISSUE TITLE
Feature request / warning: Notification banners on bottom of screen

### ISSUE THREAD

**Issue by acrookston** [hyperoslo/Whisper#30]
This seems like a great library, thanks for the hard work! I built a custom, similar component to this a while ago but will definitely be using this more full-featured gem moving forward.

My request is to have the option to display these bars on the bottom of the screen, on top or above any potential tabbar.

My warning is: I heard through the grapevine that Twitter uses the bottom-notification style because Apple thought the top-style-popdowns looked too similar (confusing the users) to the native notification banners. Maybe this could be noted in the readme?

**Comment by RamonGilabert** [comment]
Hey @acrookston happy new year and thank's for your comment! :)

The design of the notification was pretty much inspired by the one that Messenger has, but I agree that the twitter one looks really great too, in a future version, 2.0, we might add more functionality to Whisper for you to be able to display it in the bottom of the screen since now it needs to be tight to a UINavigationController and stuff, it's totally a good suggestion. :)

**Comment by idcuesta** [comment]
Hi there,

I have modified the existing implementation to support whispers from any UIViewController, and also support display from the top or the bottom.

There is a change in philosophy, as now the WhisperFactory doesn't know about concepts like insets, or rotation, it is the host controller responsibility to handle this (a default implementation is provided for UIViewController classes).

It could be applied to Murmurs and Announcements too, but wanted to see what do you think first about this.

Regards

**Comment by Danm72** [comment]
bump, this would be great.
