### ISSUE TITLE
Feature: Ability to change text colour

### ISSUE THREAD

**Issue by jaffacake** [hyperoslo/Whisper#36]
I've seen that you recently added the ability to change the background colour (which is really useful), however we want to change our background to a light green, but without being able to change the text colour it is really unreadable.

To be able to pass a text colour in addition to the background colour would be great!

**Comment by RamonGilabert** [comment]
Hey @jaffacake! Which part are you talking about? Whisper, Shout or Whistle? :)

If it's Shout you can actually change the color: #32.

By simply setting:

``` swift
ColorList.Shout.title
ColorList.Shout.subtitle
```

**Comment by jaffacake** [comment]
Sorry, I was referring to whisper. It would be good if you could implement it across all types.

**Comment by zenangst** [comment]
We could potentially add an optional property on `Message` that would set the text color of the `Whisper` if it is present. I do see the problem here that you might want to use a color that doesn't go well with the default text color.

I think the reasoning behind that a `Whisper` is being handled differently is that you potentially want each message to have its unique color to describe intent and importance where as both `Message` and `Murmur` is a more generic alternative that should be styled to fit your applications design.

@vadymmarkov @RamonGilabert  what do you guys think?

**Comment by zenangst** [comment]
@jaffacake hey, we made a pull request that just got merged into master. We are working on a new release which would be `2.0.0`. We would love to get your feedback on that when its out.

Ref: https://github.com/hyperoslo/Whisper/pull/44
