### ISSUE TITLE
Button Actions in Shout / Announcement

### ISSUE THREAD

**Issue by cannyboy** [hyperoslo/Whisper#67]
Would be great to have button actions in Shouts, like:

![Text](http://odecee.com.au/wp-content/uploads/textInputPhone.png)

![Buttons](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Art/notif_ctr_banner_actions_2x.png)

https://github.com/hyperoslo/Whisper/issues/52 might be asking the same thing

**Comment by RamonGilabert** [comment]
Hey @cannyboy! As #29 stated, that would be nice but it's not really the intention of Whisper, since Whisper is just a tiny message that you show in your UI. Plus, the native banner answers or does actions from other apps, that makes sense from a context point of view, although inside an app, you can just bring the user to where the action should take place without loosing much of the context that such user has.

With that being said, I'll close this issue and keep #29 opened.
