### ISSUE TITLE
Whistle permanent?

### ISSUE THREAD

**Issue by gali8** [hyperoslo/Whisper#73]
Is possible to use a Whistle like a permanent message?
Is possible to hide it programmatically?

**Comment by deepumukundan** [comment]
I had a similar requirement. I made some tweaks and was about to create a PR but noticed that since a whistle is in a window over the current window, it might sometimes affect some logic you might have in your code. Anyways I will create a PR to add this capability since it is an optional addition, not default behaviour.

**Comment by deepumukundan** [comment]
Added this capability in PR https://github.com/hyperoslo/Whisper/pull/76

**Comment by valeIT** [comment]
Any update?

**Comment by deepumukundan** [comment]
This has been added in v3.0 of the library by the core team itself. I had a PR for some time but then closed it as it was open for a long time.

**Comment by RamonGilabert** [comment]
Thanks for the PR @deepumukundan, closing this since it works, as you mentioned in version 3.0.
