### ISSUE TITLE
Announce from anywhere

### ISSUE THREAD

**Issue by D-Mx** [hyperoslo/Whisper#78]
Hi,
I'm trying to show a shout but I'm getting this error:

`fatal error: The controller must contain a navigation bar: file .../Pods/Whisper/Source/ShoutFactory.swift, line 154`

My use case is that I want to show when a new push notification arrives anywhere the user is but I have some ViewController that don't have a navigation bar.

**Edit**
Maybe just change this line? I don't know why it must be a navigationcontroller

``` swift
 public func shout(to controller: UIViewController) {
     //--Remove
    //guard let controller = controller.navigationController else { fatalError("The controller must contain a navigation bar") } 

    let width = UIScreen.mainScreen().bounds.width
    controller.view.addSubview(self)

    frame = CGRect(x: 0, y: 0, width: width, height: 0)
    backgroundView.frame = CGRect(x: 0, y: 0, width: width, height: 0)

    UIView.animateWithDuration(0.35, animations: {
      self.frame.size.height = Dimensions.height
      self.backgroundView.frame.size.height = self.frame.height
    })
  }

```

**Comment by iliaskarim** [comment]
@D-Mx we did the same thing on our branch -- just remove that line 🙄

**Comment by maa-x** [comment]
+1

**Comment by onmyway133** [comment]
@D-Mx this https://github.com/hyperoslo/Whisper/pull/81 fixes that by lower `fatalError` to `assertFailure`. But anyway, having `navigationController` is best in this way

**Comment by maa-x** [comment]
Not sure why it is better. At the very least it is cumbersome. It makes implementing an app wide notification handler a lot trickier. I for example made my own NavBar subclass that also handles the notifications. This works fine as long as I comment that line and I see no reason why this use wouldn't be valid.

EDIT: Also I cannot subclass UIViewController because I already have a framework that implements it - which would have been the other way I would have handle the notifications on an app wide level.

**Comment by RamonGilabert** [comment]
Hey guys! This got fixed in the new versions of Whisper! :)
