### ISSUE TITLE
Message size is incorrect 

### ISSUE THREAD

**Issue by Austinate** [hyperoslo/Whisper#90]
First of all — thanks for such nice lib! :) 

I've found 2 issues: 
1. If application is in split-screen-mode (so app window size != mainScreen size) — we have wrongly sized Message 
2. If Message is used in any kind of non-fulscreen popover/presentation controller — we have same issue 

Here is an: [example](http://i.imgur.com/BCfkMIf.png?1)

I think, proper solution will be to just get width of navigationBar, what do you think? 

P.S. Will try to create a PR with this change during the weekend

**Comment by IsmailHassanein** [comment]
I was about to open the same issue. In my case I'm using a splitView. It's not correct using the screen width. 
Thanks @Austinate   for fixing it. 
@zenangst  Please review and merge  his [pull request.](https://github.com/hyperoslo/Whisper/pull/92)

**Comment by sellingsolutions** [comment]
@Austinate @zenangst Any update on the PR?

 I've added a 0.4 sec delay before re-positioning the UILabel which ends up looking ok. This is due to the in & out animation taking 0.4 seconds to complete, which hides the fact that I'm moving the label into the visible area. 

Would be cool to not have to hack around it though! Cheers guys for writing such awesome libraries!

**Comment by ivanornes** [comment]
I have managed to fix the issue by changing the UIScreen.main.bounds with the width of the used navigation bar.  Check it [here](https://github.com/oinsider/Whisper/commit/dcd326b2da37dd1ba3a1fa489adf60c2743d1999).
